name: PyPi Publish

on:
  workflow_dispatch:  # Manually start a workflow
#  push:
#    branches:
#    - pypi_publish
#    paths-ignore:
#    - '.github/**' # Ignore changes towards the .github directory

jobs:

  build-pypi:
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Install Python
       uses: actions/setup-python@v2
       with:
         python-version: '3.7'
     - name: Install dependencies
       run: |
         sudo apt-get update
         sudo apt install libgtk-3-dev libnotify-dev libsdl2-dev
         pip install -U \
          -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04 \
          wxPython
     - name: Install requirements
       run: |
         pip install -r requirements.txt -r requirements_build.txt
         pip install -e .
     - name: Run sdist
       run: python setup.py sdist bdist_wheel
     - name: See dist directory
       run: ls dist
     - uses: actions/upload-artifact@v2
       with:
         name: sdist
         path: dist/esp_flasher-*.tar.gz
     - uses: actions/upload-artifact@v2
       with:
         name: bdist_wheel
         path: dist/esp_flasher-*.whl
     - name: Publish a Python distribution to PyPI
       uses: pypa/gh-action-pypi-publish@release/v1
       with:
         user: __token__
         password: ${{ secrets.PYPI_API_TOKEN }}
